apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8sgpt-operator
  namespace: flux-system
  labels:
    app.kubernetes.io/sops: enabled
    app.kubernetes.io/post-build-variables: enabled
spec:
  interval: 1m
  targetNamespace: k8sgpt-operator
  sourceRef:
    kind: OCIRepository
    name: oci-artifacts
  path: k8sgpt-operator
  prune: true
  wait: true
