apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - executor.testkube.io_executors.yaml
  - executor.testkube.io_webhooks.yaml
  - tests.testkube.io_scripts.yaml
  - tests.testkube.io_templates.yaml
  - tests.testkube.io_testexecutions.yaml
  - tests.testkube.io_tests.yaml
  - tests.testkube.io_testsources.yaml
  - tests.testkube.io_testsuiteexecutions.yaml
  - tests.testkube.io_testsuites.yaml
  - tests.testkube.io_testtriggers.yaml
  - testworkflows.testkube.io_testworkflowexecutions.yaml
  - testworkflows.testkube.io_testworkflows.yaml
  - testworkflows.testkube.io_testworkflowtemplates.yaml
