apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    app.kubernetes.io/remediation: enabled
    app.kubernetes.io/crds: enabled
spec:
  interval: 1m
  chart:
    spec:
      chart: longhorn
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
  # https://github.com/longhorn/charts/blob/v1.7.x/charts/longhorn/values.yaml
  values:
    persistence:
      defaultDataLocality: best-effort
    ingress:
      enabled: true
      host: longhorn.${cluster_domain}
      ingressClassName: ${ingress_class_name:=}
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Longhorn
        gethomepage.dev/description: Cloud-native storage.
        gethomepage.dev/group: Storage
        gethomepage.dev/icon: longhorn
        gethomepage.dev/app: longhorn-dashboard
        gethomepage.dev/pod-selector: app.kubernetes.io/name=longhorn
