apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
spec:
  interval: 5m
  dependsOn:
    - name: metrics-server
      namespace: metrics-server
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: vertical-pod-autoscaler
      version: 9.5.0
      sourceRef:
        kind: HelmRepository
        name: vertical-pod-autoscaler
  # https://github.com/cowboysysop/charts/blob/master/charts/vertical-pod-autoscaler/values.yaml
  values: {}
