apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubelet-serving-cert-approver
resources:
  - certificates-cluster-role.yaml
  - cluster-role-binding.yaml
  - deployment.yaml
  - events-role.yaml
  - leader-election-role.yaml
  - namespace.yaml
  - service-account.yaml
  - service.yaml
