apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.9/manifests/install.yaml
  - ingress-staging.yaml
patchesStrategicMerge:
  - argocd-cmd-params-cm-patch.yaml
namespace: argocd