apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fleetdm
  namespace: fleetdm
  labels:
    app.kubernetes.io/remediation: enabled
    app.kubernetes.io/crds: enabled
spec:
  interval: 10m
  chart:
    spec:
      chart: fleet
      version: v6.2.0
      sourceRef:
        kind: HelmRepository
        name: fleetdm
  # https://github.com/fleetdm/fleet/blob/main/charts/fleet/values.yaml
  values:
    resources: {}
    hostName: fleetdm.${cluster_domain}
    ingress:
      enabled: true
      hosts:
        - host: fleetdm.${cluster_domain}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: {}
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Fleet Device Management
        gethomepage.dev/description: Open-source device management platform.
        gethomepage.dev/group: Provisioning
        gethomepage.dev/icon: si-coderwall-#40B5A4
    fleet:
      tls:
        enabled: false
    database:
      address: fleetdm-mysql.fleetdm:3306
    cache:
      address: fleetdm-redis-master.fleetdm:6379
      usePassword: true
    # https://github.com/bitnami/charts/blob/main/bitnami/mysql/values.yaml
    mysql:
      enabled: true
      auth:
        createDatabase: true
        database: fleet
        username: fleet
        existingSecret: mysql
    # https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
    redis:
      enabled: true
      auth:
        existingSecret: redis
        existingSecretPasswordKey: redis-password
