apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
  labels:
    app.kubernetes.io/sops: enabled
    app.kubernetes.io/post-build-variables: enabled
spec:
  interval: 1m
  targetNamespace: kyverno
  sourceRef:
    kind: OCIRepository
    name: oci-artifacts
  path: kyverno
  prune: true
  wait: true
