apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pulumi-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: pulumi-kubernetes-operator
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: pulumi-operator
  # https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/deploy/helm/pulumi-operator/values.yaml
  values:
    extraVolumes:
      - name: backend-data
        persistentVolumeClaim:
        claimName: pulumi-backend-pvc
    extraVolumeMounts:
      - name: backend-data
        mountPath: ${pulumi_backend_path}
