apiVersion: v1
kind: Namespace
metadata:
  name: capi-operator-system
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    goldilocks.fairwinds.com/vpa-min-replicas: "1"
    goldilocks.fairwinds.com/vpa-update-mode: "auto"
