apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
  labels:
    app.kubernetes.io/sops: enabled
    app.kubernetes.io/post-build-variables: enabled
spec:
  interval: 1m
  targetNamespace: kube-system
  sourceRef:
    kind: OCIRepository
    name: oci-artifacts
  path: metrics-server
  prune: true
  wait: true
