apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  # https://github.com/jameswynn/helm-charts/blob/main/charts/homepage/values.yaml
  # Icons:
  # https://github.com/walkxcode/dashboard-icons No prefix
  # https://pictogrammers.com/library/mdi/ Prefix with mdi-
  # https://simpleicons.org/ Prefix with si-
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v0.8.13
    ingress:
      main:
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-traefik-forward-auth@kubernetescrd
    config:
      settings:
        title: Homelab
        theme: dark
        color: slate
        background:
          image: https://images.unsplash.com/photo-1512652683497-9d8ee4641be1?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
          blur: sm
          saturate: 50
          brightness: 50
          opacity: 50
        providers:
          longhorn:
            url: http://longhorn-frontend.longhorn-system:80
      widgets:
        - resources:
            backend: kubernetes
            expanded: true
            cpu: true
            memory: true
        - search:
            provider: google
            target: _blank
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - longhorn:
            expanded: true
            total: true
            labels: true
            nodes: true
        - datetime:
            text_size: xl
            format:
              timeStyle: short
      services:
        - Websites:
            - GitHub Pages:
                icon: github
                href: https://${cluster_domain}
                description: Personal website and blog.
        - Networking:
            - Cloudflare:
                icon: cloudflare
                href: https://cloudflare.${cluster_domain}
                description: Central hub for managing public networking, e.g. FQDN, DNS and remote tunneling.
            - UniFi:
                icon: unifi
                href: https://unifi.ui.com
                description: Central hub for managing on-prem UniFi network infrastructure.
        - Provisioning:
            - Omni:
                icon: si-talos-#FF7300
                href: https://omni.${cluster_domain}
                description: Platform for provisioning and managing Talos Linux clusters.
        - Storage:
            - Longhorn:
                icon: longhorn
                href: https://longhorn.${cluster_domain}
                description: Cloud-native storage.
                app: longhorn
                namespace: longhorn-system
            - Harbor:
                icon: harbor
                href: https://harbor.${cluster_domain}
                description: Cloud-native Container Registry.
                app: harbor
                namespace: harbor
        - Monitoring:
            - Cilium Hubble:
                icon: cilium
                href: https://hubble-ui.${cluster_domain}
                description: Observability for Cilium, a high-performance Container Network Interface (CNI).
                app: hubble-ui
                namespace: kube-system
            - Goldilocks:
                icon: mdi-white-balance-sunny
                href: https://goldilocks.${cluster_domain}
                description: Dashboard for automated vertical pod autoscaling recommendations.
                app: goldilocks
                namespace: goldilocks
            - Traefik:
                icon: traefik
                href: https://traefik.${cluster_domain}
                description: Dashboard for Reverse Proxy.
                app: traefik
                namespace: traefik
      bookmarks:
        - News:
            - GitHub Blog:
                - icon: github
                  href: https://github.blog
            - CNCF Blog:
                - icon: si-cncf-#231F20
                  href: https://www.cncf.io/blog
            - OpenAI Blog:
                - icon: openai
                  href: https://openai.com/blog
        - Releases:
            - VSCode Releases:
                - icon: vscode
                  href: https://code.visualstudio.com/updates
        - Development:
            - GitHub:
                - icon: github
                  href: https://github.com
            - Renovate:
                - icon: si-renovatebot-#1A1F6C
                  href: https://developer.mend.io
