name: Promote

on:
  push:
    paths:
      - ".github/workflows/promote.yaml"
      - "k8s/**/*.yaml"
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‘ Checkout
        uses: actions/checkout@v4
      # - name: "â° Wait for sandbox deployment to finish"
      #   uses: autotelic/action-wait-for-status-check@v1
      #   id: wait-for-sandbox
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     statusName: "kustomization/flux-system/79be6292"
      # - name: Promote deployment to production
      #   if: steps.wait-for-sandbox.outputs.state == 'success'
      #   uses: joelwmale/webhook-action@master
      #   with:
      #     url: ${{ secrets.WEBHOOK_URL }}
      #     headers: '{"repository": "joelwmale/webhook-action"}'
      #     body: '{"event": "deployment", "repository": "joelwmale/webhook-action"}'
      # - if: steps.wait-for-sandbox.outputs.state == 'failure'
      #   run: exit 1

      # Rollbacks
      # - name: "ğŸ”™ Rollback production deployment"
      #   if: failure()
      # - name: "ğŸ”™ Rollback staging deployment"
      #   if: failure()
      # - name: "ğŸ”™ Rollback sandbox deployment"
      #   if: failure()
