apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  releaseName: cilium
  targetNamespace: kube-system
  storageNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 12h
  values:
    ipam:
      mode: kubernetes
    operator:
      replicas: 1
